name: shpeucfmobile
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  supabase_flutter: ^2.9.1
  flutter_svg: ^2.0.7
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  qr_code_scanner_plus: ^2.0.10+1
  image_picker: ^1.0.7
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  http: ^0.13.5
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/images/background.png
    - lib/images/SHPE_LogoU.png
    - lib/images/SHPE_Logo.svg
    - lib/images/Calendar.png
    - lib/images/Home.png
    - lib/images/Leaderboard.png
    - lib/images/Pictures.png
    - lib/images/Qr.png
    - lib/images/Profile2.png
    - lib/images/SHPE.png
    - lib/images/topOfLeaderboard.png
    - lib/images/Leaderboard.png
    - lib/images/leaderboardWord.png
    - lib/images/leaderboardWord2.png
    - lib/images/topOfLeaderboard.svg
    - lib/images/events.png
    - lib/images/profile1.svg
    - lib/images/ProfileBackground.jpeg
    - lib/images/SHPE2.png
    - lib/images/backbutton.png
    - lib/images/testImage1.jpg
    - lib/images/test3.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Adumu
      fonts:
        - asset: fonts/Adumu.ttf
